// <auto-generated />
namespace XYZschool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class plural : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(plural));
        
        string IMigrationMetadata.Id
        {
            get { return "201908091840326_plural"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
